# Little Computer People color theme for Helix
# by Mikael SÃ¤ker.

# "ui.background" = { bg = "background" }
# "ui.text" = "foreground"
# "ui.text.info" = "foreground"
# "ui.statusline" = "darkblue"
# "ui.cursor" = { fg = "foreground", bg = "lightblue" }
# "ui.cursor.match" = { bg = "lightblue" }
# "ui.cursor.primary" = { fg = "foreground", bg = "blue" }
# "ui.selection" = { bg = "lightblue" }
# "ui.menu" = { fg = "foreground", bg = "sand" }
# "ui.menu.selected" = { fg = "background", bg = "darkblue" }
# "ui.popup" = { fg = "foreground", bg = "sand" }
# "ui.help" = { fg = "background", bg = "darkblue" }
# "ui.linenr" = "grey"
# "ui.linenr.selected" = "darkgrey"
# "ui.window" = { fg = "darkblue" }

"ui.background" = { bg = "background" }
"ui.text" = "foreground"
"ui.text.info" = "background"
"ui.text.focus" = { bg = "darkblue", fg = "background" }
"ui.statusline" = "darkblue"
"ui.cursor" = { fg = "foreground", bg = "lightblue" }
"ui.cursor.match" = { bg = "lightblue" }
"ui.cursor.primary" = { fg = "foreground", bg = "blue" }
"ui.selection" = { bg = "blue" }
"ui.selection.primary" = { bg = "lightblue" }
"ui.menu" = { fg = "foreground", bg = "background" }
"ui.menu.selected" = { fg = "background", bg = "darkblue" }
"ui.popup" = { fg = "background", bg = "blue" }
"ui.popup.info" = { fg = "background", bg = "darkblue" }
"ui.help" = { fg = "background", bg = "darkblue" }
"ui.linenr" = "grey"
"ui.linenr.selected" = "darkgrey"
"ui.highlight" = { fg = "red", bg = "blue"}

"warning" = "yellow"
"error" = { fg = "red" }
"info" = { fg = "blue", modifiers = ["bold"] }
"hint" = { fg = "blue", modifiers = ["bold"] }

"diagnostic.hint" = { underline = { color = "blue", style = "curl" } }
"diagnostic.info" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.warning" = { underline = { color = "orange", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

"comment" = { fg = "red", modifiers = ["italic"] }
"string" = { modifiers = ["italic"] }
"keyword" = { modifiers = ["bold"] }
"markup.heading" = { modifiers = ["bold"] }
"markup.heading.marker" = { fg = "red", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "blue" }
"diff.minus" = { fg = "red" }

[palette]
foreground = "#1a1a1a"
background = "#f7f7f7"
grey = "#d5d5d5"
darkgrey = "#858585"
red = "#f2291a"
blue = "#20bbfc"
lightblue = "#a6e4fe"
darkblue = "#105e7e"
green = "#86b300"
orange = "#E67E25"
yellow = "#F0C418"
